 version: "3"
 services:
  db:
    build: .
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: resbar
 volumes:
  db-data:
